
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/personnel-societe
    password: ''
  h2:
    console:
      enabled: 'true'
  application:
    name: societe-personnel
  liquibase:
    enabled: 'true'
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none